#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

IFDOWN="*"

for f in /etc/openssh-initramfs-crypt-unlock/config.d/*.conf; do
    # If no match happens. Bc nullglob doesn't exist for dash
    if [ -f "$f" ] && [ -r "$f" ]; then
        . "$f"
    fi
done

for IFACE in /sys/class/net/${IFDOWN}; do
    [ -e "$IFACE" ] || continue
    IFACE="${IFACE#/sys/class/net/}"
    ip link    set   dev "$IFACE" down
    ip address flush dev "$IFACE"
    ip route   flush dev "$IFACE"
done
